### ISSUE TITLE
Adicionar a checagem do DDI na anotação @PhoneBrazil

### ISSUE THREAD

**Issue by jonatas0072** [muriloalvesdev/thehero-backend#49]
**Motivação**
Foi feito a anotação @PhoneBrazil para validar telefones brasileiros, no entanto, ela valida o DDD mais o numero de telefone com o nono digito. Para que seja realmente oficial o numero brasileiro à necessidade de se validar se os três primeiros dígitos informados é +55, correspondente ao DDI do Brasil.

**Comment by muriloalvesdev** [comment]
@jonatas0072 Você pode usar o próprio regex pra isso. O interessante seria adicionar um teste realizando uma requisição bem sucedida e outra mal sucedida. Realizei testes manuais, desculpe. Para que fique de seu conhecimento, o teste do "caminho triste" deve esperar o status 400.
